project_id = "ttepglsqnbevhtxrqayq"

[functions.webhook-send]
verify_jwt = true

[functions.webhook-review]
verify_jwt = true

[functions.webhook-deliver]
verify_jwt = true

[functions.download-zip]
verify_jwt = true

[functions.mapbox-geocoding]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.check-email-verified]
verify_jwt = false
